"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['resources/background.jpeg','resources/block.jpg',
              'resources/cavatappi.jpg','resources/nomnom.mp3','resources/yummy.mp3',
              'resources/snake_music.mp3']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
